import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Syne } from "@/fonts/syne";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Syne.className} bg-black relative`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
